name: SDL
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/**'

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  # github.ref is not unique in post-commit
  group: ${{ github.event_name == 'push' && github.run_id || github.ref }}-linux-sdl
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  sdl_tests:
    name: OpenVINO tokenizers sdl tests
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    env:
      OPENVINO_TOKENIZERS_REPO: ${{ github.workspace }}/openvino_tokenizers

    steps:
      - name: Clone Openvino tokenizers sources and tests
        uses: actions/checkout@v4
        with:
          path: ${{ env.OPENVINO_TOKENIZERS_REPO }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Python tests dependencies
        run: |
          python3 -m pip install bandit

      - name: Tokenizers Bandit tests
        run: |
          bandit -c pyproject.toml -r python
        working-directory: ${{ env.OPENVINO_TOKENIZERS_REPO }}

  trivy_scan:
    name: code_scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      # - name: Run Trivy vulnerability scanner in repo mode
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     ignore-unfixed: true
      #     format: 'sarif'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: 'trivy-results.sarif'

      # - name: Upload Trivy scan results
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy_results
      #     path: 'trivy-results.sarif'
      #     if-no-files-found: 'error'
